
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
    username: root
    password: 123456
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j

    #配置redis数据库连接
    redis:
          # Redis数据库索引（默认为0）
          database: 0
          # Redis服务器地址
          host: localhost
          # Redis服务器连接端
          port: 6379
          # Redis服务器连接密码
    #      password: root
          pool:
          # 连接池最大连接数（使用负值表示没有限制）
              max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
              max-wait: -1
          # 连接池中的最小空闲连接
              min-idle: 0
          # 连接池中的最大空闲连接
              max-idle: 8
    # 连接超时时间（毫秒）
          timeout: 0
#  jpa:
#    database: MySQL
#    show-sql: true
#    hibernate:
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      ddl-auto: update

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.winter.model  # 注意：对应实体类的路径

  thymeleaf:
    suffix: .jsp
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

